### ISSUE TITLE
spoofing of X-Forwarded-For header

### ISSUE THREAD

**Issue by azio7** [hacdias/webdav#189]
the server trust every X-Forwarded-For header which can be spoofed
![image](https://github.com/user-attachments/assets/990b8d22-d4e4-418f-a5b0-97cd81ca50a8)
i recommend adding a trusted upstream list option in config, it could be 172.17.0.0/16 or 127.0.0.1/32

**Comment by hacdias** [comment]
Hi,

Thanks for the report. I see how this could be a problem. I see two possible solutions:

1. Use a whitelist just like you said. That requires the server to process all the IPs and match them against the whitelist. 
2. A new option in the configuration to indicate whether or not the server is behind a trusted proxy. It it is behind a trusted proxy, we trust the header. Otherwise, just use the remote address. 

I'm more inclined for 2, because most people will be running this behind a reverse proxy and most reverse proxies can be configured to correctly handle the sanitisation of this header. And if you're not using a reverse proxy, there's no reason to trust the header.

**Comment by azio7** [comment]
the option 2 is what i mean

**Comment by azio7** [comment]
you might mistake my thought. it is my fault, i have a better example.
 https://docs.ctf.gzti.me/config/appsettings

see ForwardedOptions

**Comment by hacdias** [comment]
I understood your suggestion. That was option 1: adding a whitelist. But as I said, I don't see why that would be needed. In most situations you have:

- Or is the server directly exposed to the Internet and then you don't have a proxy. In this case you'll never trust the header. 
- Or is the server behind a reverse proxy. In this case you can always trust the header. 

The only situation that I could imagine you'd want a whitelist is if you have the server both directly exposed and also behind a reverse proxy. However, is that a realistic scenario? I'm curious.

**Comment by azio7** [comment]
yes,in most case is ok with a bool type. but there is another case of misconfiguration. by default, nginx does not override the x-forward-for header. i believe dont trust reverse proxy is better

**Comment by azio7** [comment]
yes, in most case it is ok. before I thought that hackers could bypass the proxy to attack your software, now I think that your software may not need to be so demanding
