### ISSUE TITLE
Create/Edit/Delete as separate permissions

### ISSUE THREAD

**Issue by priyadarshan** [hacdias/webdav#19]
Hello,

I have just found out about Caddy-webdav, and I am enthusiastic about it. We already have it running on some servers with excellent results.

Right now permissions can be set to access and/or change a resource.

I was wondering if it could be possible to add independent permissions? Like:
- create only
- change only
- delete only

Currently we do use combinations of those permissions on some webdav shares, through NextCloud (see screenshot).

![webdav-access-options](https://user-images.githubusercontent.com/1652143/36072052-2e8f8c30-0f19-11e8-9067-36e1cb953129.png)

We do not need all the infrastructure NextCloud offers, and the additional complex toolchain that imposes.

It would be fantastic if Caddy-webdav could completely replace NextCloud's role as webdav server .

Thank you for making Caddy-webdav available, it is a wonderful addition to Caddy.

**Comment by hacdias** [comment]
This will be slightly more complicated than I expected, since `PROPPATCH` calls can include multiple modifications and deletions, and those would be separate permissions.

Either way, the implementation could go two ways:

- Or a variable per permission; or
- A string to set the different permissions, e.g. `permissions: CRU` for "Create", "Read", "Update". This could also replace the `modify` and `allow` in the rules, since all the permissions could be condensed to a single parameter.
