### ISSUE TITLE
error on line 1 at column 1530: Extra content at the end of the document

### ISSUE THREAD

**Issue by ctaoist** [hacdias/webdav#55]
os：archlinux x64
webdav version: v3.1.2

error is as follows:
![TIM截图20201031215828](https://user-images.githubusercontent.com/14012127/97781099-1d0f1600-1bc4-11eb-9786-b8b2f4d48d90.png)

and webdav' output in terminal:
```
2020/10/31 21:55:22 http: superfluous response.WriteHeader call from golang.org/x/net/webdav.(*Handler).ServeHTTP (webdav.go:74)
```

**Comment by Mohammed90** [comment]
This is coming from the golang.org/x/net/webdav package. The culprit in that library is here:

https://github.com/golang/net/blob/69a78807bb2bb6d1599c68698c6b009505012083/webdav/webdav.go#L73-L78

and here:

https://github.com/golang/net/blob/69a78807bb2bb6d1599c68698c6b009505012083/webdav/webdav.go#L476-L483

**Comment by FanNengHu** [comment]
I also encountered this problem on the win10. Later, I found out that it was because one folder did not have permission to read it.When I gave the folder read permission, the problem was solved. You can click on each folder to see if you have permission to read it.

However, If you still can't find the problem. you can change the tool to caddy(with external webdav plugins). There are specific error prompts on caddy.

When you have solved the problem of caddy, You can use this tool normally at the same time. Because both tools are based on the same framework.

**Comment by hacdias** [comment]
I will close this for now. If this is still a problem now or in the future, please feel free to open a new issue. In either case, this is likely to be an issue in the upstream repository that @mohammed90 linked above.
